nmxact/udp: Fix image upload failure due to unsupported async method
This addresses the UDP based image upload failure.

The UDP and naked sessons do not implement TxRxAsync
for optimized transfer as in BLE, however, continue to
support the operation by calling TxRxMgmt.

Failure signature:
~/go/bin/mcumgr --conntype udp --connstring=[192.168.1.1]:1337 image
upload build_f429/smpsvr/zephyr/zephyr.signed.bin
0 / 90644
[-----------------------------------------]
0.00%
Error: ImageUpload unexpected error after 0/90644 bytes

Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>