bll_sesn_cfg_windows: Fix build error for windows
Commit 0663961c537af3cfebee51854c515917c5bff804 replaced callbacks
with interfaces (TxFilter and RxFilter). Apply the change for
the Windows specific implementation as well and fix the following
error.

C:\Users\ryan.erickson>go get github.com/apache/mynewt-mcumgr-cli/mcumgr
go\src\mynewt.apache.org\newtmgr\newtmgr\bll\bll_sesn_cfg_windows.go:35:15:
undefined: nmcoap.MsgFilter
go\src\mynewt.apache.org\newtmgr\newtmgr\bll\bll_sesn_cfg_windows.go:36:15:
undefined: nmcoap.MsgFilter

Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>